export const ADD_PRODUCT = 'ADD_PROUDCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';

export const SET_PRODUCTS = 'SET_PRODUCTS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';